import { describe, it, expect } from 'bun:test';
import path from 'path';

import { getLaunchdLabel } from '../src/install-slug.js';

/**
 * Tests for service configuration generation.
 *
 * These tests verify the generated content of bundle/plist/systemd/nohup
 * configs without actually loading services. The generators here mirror
 * those in setup/service.ts; if you change the format there, mirror the
 * change here so the tests still gate the real config.
 */

// Helper: generate the launchd plist string the same way service.ts does.
// Bun version (post-bun-migration): the plist points at the bundle's MacOS
// executable, not directly at bun.
function generatePlist(
  bundleExecPath: string,
  projectRoot: string,
  homeDir: string,
): string {
  const label = getLaunchdLabel(projectRoot);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${bundleExecPath}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${projectRoot}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:${homeDir}/.local/bin</string>
        <key>HOME</key>
        <string>${homeDir}</string>
    </dict>
    <key>StandardOutPath</key>
    <string>${projectRoot}/logs/nanoclaw.log</string>
    <key>StandardErrorPath</key>
    <string>${projectRoot}/logs/nanoclaw.error.log</string>
</dict>
</plist>`;
}

function generateBundleInfoPlist(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>com.nanoclaw.homestead-nanobot</string>
    <key>CFBundleName</key>
    <string>Homestead Nanobot</string>
    <key>CFBundleDisplayName</key>
    <string>Homestead Nanobot</string>
    <key>CFBundleExecutable</key>
    <string>homestead-nanobot</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>LSBackgroundOnly</key>
    <true/>
</dict>
</plist>`;
}

function generateBundleWrapper(bunPath: string, projectRoot: string): string {
  return `#!/bin/bash
# Homestead Nanobot launcher — generated by setup/service.ts.
# Edit by re-running pnpm/bun setup, not by hand (will be overwritten).
exec ${JSON.stringify(bunPath)} run ${JSON.stringify(path.join(projectRoot, 'src/index.ts'))}
`;
}

function generateSystemdUnit(
  bunPath: string,
  projectRoot: string,
  homeDir: string,
  isSystem: boolean,
): string {
  return `[Unit]
Description=NanoClaw Personal Assistant
After=network.target

[Service]
Type=simple
ExecStart=${bunPath} run ${projectRoot}/src/index.ts
WorkingDirectory=${projectRoot}
Restart=always
RestartSec=5
KillMode=process
Environment=HOME=${homeDir}
Environment=PATH=/usr/local/bin:/usr/bin:/bin:${homeDir}/.local/bin
StandardOutput=append:${projectRoot}/logs/nanoclaw.log
StandardError=append:${projectRoot}/logs/nanoclaw.error.log

[Install]
WantedBy=${isSystem ? 'multi-user.target' : 'default.target'}`;
}

const HOME = '/home/user';
const ROOT = '/home/user/nanoclaw';
const BUNDLE_EXEC = `${HOME}/Applications/Homestead Nanobot.app/Contents/MacOS/homestead-nanobot`;

describe('plist generation', () => {
  it('contains the slug-scoped label', () => {
    const plist = generatePlist(BUNDLE_EXEC, ROOT, HOME);
    expect(plist).toContain(`<string>${getLaunchdLabel(ROOT)}</string>`);
    expect(plist).toMatch(/<string>com\.nanoclaw-v2-[0-9a-f]{8}<\/string>/);
  });

  it('points at the bundle wrapper, not at bun directly (so BTM attributes the item to the Homestead Nanobot bundle, not to bun)', () => {
    const plist = generatePlist(BUNDLE_EXEC, ROOT, HOME);
    expect(plist).toContain(`<string>${BUNDLE_EXEC}</string>`);
    expect(plist).not.toContain('<string>/opt/homebrew/bin/bun</string>');
  });

  it('does not reference the deleted dist/index.js (Bun runs src/ directly)', () => {
    const plist = generatePlist(BUNDLE_EXEC, ROOT, HOME);
    expect(plist).not.toContain('dist/index.js');
  });

  it('has /opt/homebrew/bin first on PATH so the wrapper finds bun on Apple Silicon Macs', () => {
    const plist = generatePlist(BUNDLE_EXEC, ROOT, HOME);
    expect(plist).toContain('/opt/homebrew/bin:');
  });

  it('sets log paths', () => {
    const plist = generatePlist(BUNDLE_EXEC, ROOT, HOME);
    expect(plist).toContain('nanoclaw.log');
    expect(plist).toContain('nanoclaw.error.log');
  });
});

describe('bundle Info.plist generation', () => {
  it('declares CFBundleName="Homestead Nanobot" so BTM displays a friendly name', () => {
    const info = generateBundleInfoPlist();
    expect(info).toContain('<key>CFBundleName</key>');
    expect(info).toMatch(/<key>CFBundleName<\/key>\s*<string>Homestead Nanobot<\/string>/);
  });

  it('marks the bundle background-only so it does not appear in the Dock', () => {
    const info = generateBundleInfoPlist();
    expect(info).toContain('<key>LSUIElement</key>');
    expect(info).toContain('<key>LSBackgroundOnly</key>');
  });

  it('uses a stable bundle identifier', () => {
    const info = generateBundleInfoPlist();
    expect(info).toContain('<string>com.nanoclaw.homestead-nanobot</string>');
  });

  it('CFBundleExecutable matches the wrapper script filename in MacOS/', () => {
    const info = generateBundleInfoPlist();
    expect(info).toContain('<string>homestead-nanobot</string>');
  });
});

describe('bundle wrapper script generation', () => {
  it('execs bun with the absolute path to src/index.ts', () => {
    const wrapper = generateBundleWrapper('/opt/homebrew/bin/bun', ROOT);
    expect(wrapper).toContain('#!/bin/bash');
    expect(wrapper).toContain('exec "/opt/homebrew/bin/bun"');
    expect(wrapper).toContain(`"${ROOT}/src/index.ts"`);
  });

  it('does not reference dist/ (no build step under Bun)', () => {
    const wrapper = generateBundleWrapper('/opt/homebrew/bin/bun', ROOT);
    expect(wrapper).not.toContain('dist');
  });
});

describe('systemd unit generation', () => {
  it('user unit uses default.target', () => {
    const unit = generateSystemdUnit('/opt/homebrew/bin/bun', ROOT, HOME, false);
    expect(unit).toContain('WantedBy=default.target');
  });

  it('system unit uses multi-user.target', () => {
    const unit = generateSystemdUnit('/opt/homebrew/bin/bun', ROOT, HOME, true);
    expect(unit).toContain('WantedBy=multi-user.target');
  });

  it('contains restart policy', () => {
    const unit = generateSystemdUnit('/opt/homebrew/bin/bun', ROOT, HOME, false);
    expect(unit).toContain('Restart=always');
    expect(unit).toContain('RestartSec=5');
  });

  it('uses KillMode=process to preserve detached children', () => {
    const unit = generateSystemdUnit('/opt/homebrew/bin/bun', ROOT, HOME, false);
    expect(unit).toContain('KillMode=process');
  });

  it('ExecStart invokes bun on src/index.ts (no compile step)', () => {
    const unit = generateSystemdUnit('/usr/local/bin/bun', '/srv/nanoclaw', HOME, false);
    expect(unit).toContain('ExecStart=/usr/local/bin/bun run /srv/nanoclaw/src/index.ts');
    expect(unit).not.toContain('dist/index.js');
    expect(unit).not.toContain('node ');
  });
});

describe('WSL nohup fallback', () => {
  it('generates a wrapper script that nohups bun against src/index.ts', () => {
    const bunPath = '/opt/homebrew/bin/bun';
    const projectRoot = '/home/user/nanoclaw';
    const pidFile = path.join(projectRoot, 'nanoclaw.pid');

    // Mirror of the format service.ts emits in setupNohupFallback.
    const wrapper = `#!/bin/bash
set -euo pipefail
cd ${JSON.stringify(projectRoot)}
nohup ${JSON.stringify(bunPath)} run ${JSON.stringify(projectRoot + '/src/index.ts')} >> ${JSON.stringify(projectRoot)}/logs/nanoclaw.log 2>> ${JSON.stringify(projectRoot)}/logs/nanoclaw.error.log &
echo $! > ${JSON.stringify(pidFile)}`;

    expect(wrapper).toContain('#!/bin/bash');
    expect(wrapper).toContain('nohup');
    expect(wrapper).toContain(bunPath);
    expect(wrapper).toContain('src/index.ts');
    expect(wrapper).not.toContain('dist/index.js');
    expect(wrapper).toContain('nanoclaw.pid');
  });
});
